/** Stable public error codes — mirror api/_lib/public-api-error.js */
export const PUBLIC_ERROR_CODES = {
  PASSES_UNAVAILABLE: 'passes_unavailable',
  EVENT_NOT_FOUND: 'event_not_found',
  SERVICE_UNAVAILABLE: 'service_unavailable',
  INVALID_PROMO_CODE: 'invalid_promo_code',
  INSUFFICIENT_STOCK: 'insufficient_stock',
  PAYMENT_UNAVAILABLE: 'payment_unavailable',
  PRESALE_CODE_INVALID: 'presale_code_invalid',
  PRESALE_CODE_EXHAUSTED: 'presale_code_exhausted',
  PRESALE_UNAVAILABLE: 'presale_unavailable',
  PRESALE_ACCESS_REQUIRED: 'presale_access_required',
  RATE_LIMITED: 'rate_limited',
  VALIDATION_FAILED: 'validation_failed',
  RECAPTCHA_FAILED: 'recaptcha_failed',
  ORDER_NOT_FOUND: 'order_not_found',
  PAYMENT_FAILED: 'payment_failed',
  PAYMENT_UNKNOWN: 'payment_unknown',
  INVALID_REQUEST: 'invalid_request',
  EVENT_NOT_AVAILABLE: 'event_not_available',
  PASS_NOT_AVAILABLE: 'pass_not_available',
  PAYMENT_METHOD_NOT_ALLOWED: 'payment_method_not_allowed',
  AMBASSADOR_NOT_FOUND: 'ambassador_not_found',
  AMBASSADOR_UNAVAILABLE: 'ambassador_unavailable',
  TOO_MANY_ORDERS: 'too_many_orders',
  INVALID_ACCESS: 'invalid_access',
  ACADEMY_SOLD_OUT: 'academy_sold_out',
  ACADEMY_CLOSED: 'academy_closed',
  REGISTRATION_EXPIRED: 'registration_expired',
  REGISTRATION_NOT_FOUND: 'registration_not_found',
  SUBMISSION_FAILED: 'submission_failed',
  DUPLICATE_APPLICATION: 'duplicate_application',
  FORM_UNAVAILABLE: 'form_unavailable',
  GENERIC: 'generic_error',
  NETWORK: 'network_error',
} as const;

export type PublicErrorCode = (typeof PUBLIC_ERROR_CODES)[keyof typeof PUBLIC_ERROR_CODES];
